### ISSUE TITLE
Confusing blank screen after summary

### ISSUE THREAD

**Issue by kyzentun** [freem/ultralight#2]
After the summary screen is a confusing blank screen with nothing displayed.  Hitting start advances to the main title screen.

**Comment by freem** [comment]
Is there any chance you could get me the name of the screen using the F3 debug menu? It should be in the theme section (F6).

edit: I have a reason to think it's ScreenGameOver, but I'd like to be sure.

**Comment by freem** [comment]
&lt;freem_inc&gt; Kyzentun: I poked issue #2 on ultralight since I couldn't think of what screen you were talking about
&lt;Kyzentun&gt; freem_inc: ScreenGameOver

Fixed in commit 12d3bd54097ae317c11b5721b5eb11ae4cb34128
